[package]
name = "grrs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "prime_normal"
path = "src/prime_normal.rs"

[[bin]]
name = "prime_miller"
path = "src/prime_normal.rs"

[dependencies]
rand = "0.8.5"